[package]
name = "ipc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "1.0.0", features = ["os-poll", "net"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[dev-dependencies]
clap = { version = "4.5.9", features = ["derive"] }
